name: score_following

channels:
  - defaults

dependencies:
  - scipy==1.1.0
  - tqdm==4.23.4
  - numpy==1.14.3
  - matplotlib==2.2.2
  - seaborn==0.8.1
  - setuptools==39.2.0
  - cloudpickle==0.5.3
  - PyYAML==3.12
  - Cython==0.28.3

  - pip:
    - madmom==0.15.1
    - torch==0.3.1
    - pynput==1.3.7
    - tensorflow==1.5.0
    - tensorboardX==1.2
    - PyAudio==0.2.11
    - opencv_python==3.3.0.9
    - gym==0.10.5
