name: score_following

channels:
  - pytorch
  - defaults

dependencies:
  - python=3.8
  - scipy
  - tqdm
  - numpy
  - matplotlib
  - setuptools
  - cloudpickle
  - PyYAML
  - Cython
  - pytorch

  - pip:
    - madmom==0.16.1
    - pynput
    - tensorboard
    - PyAudio
    - opencv_python
    - gym
    - pretty-midi
    - pysoundfile
    - pyfluidsynth
    - nose
    - mock
    - librosa
    - tensorflow